site_name: Evrmore Authentication
site_url: https://manticoretechnologies.github.io/evrmore-authentication/
site_description: Secure blockchain-based authentication using Evrmore wallet signatures
site_author: Manticore Technologies
repo_url: https://github.com/manticoretechnologies/evrmore-authentication
repo_name: manticoretechnologies/evrmore-authentication

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  logo: docs/assets/images/logo.svg
  favicon: docs/assets/images/logo.svg
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight

nav:
  - Home: index.md
  - User Guide:
    - Introduction: user-guide/index.md
    - Authentication Flow: user-guide/authentication-flow.md
    - Basic Integration: user-guide/basic-integration.md
    - OAuth 2.0 Implementation: user-guide/oauth-implementation.md
    - Debugging & Advanced Features: user-guide/debugging.md
    - Troubleshooting: user-guide/troubleshooting.md
  - API Reference:
    - Overview: api-reference/index.md
    - Core Auth API: api-reference/core-api.md
    - OAuth 2.0 API: api-reference/oauth-api.md
    - SQLite Implementation: api-reference/sqlite.md
    - Event Hooks: api-reference/event-hooks.md
  - Examples:
    - Overview: examples/index.md
    - Basic Authentication Demo: examples/basic-demo.md
    - FastAPI Integration: examples/fastapi-integration.md
    - OAuth 2.0 Client: examples/oauth-client.md
  - Development:
    - Getting Started: development/index.md
    - Testing: development/testing.md
    - Contributing: development/contributing.md
    - Security: development/security.md
    - Release Process: development/release-process.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/manticoretechnologies
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/evrmore-authentication/
  
copyright: Copyright &copy; 2023-2024 Manticore Technologies 